platform: linux
image_resource:
  type: docker-image
  source:
    repository: neilellis/easydeploy-java-mvn-base
    tag: latest

inputs:
  - name: se-labs
  - name: version

outputs:
  - name: build

run:
  path: ./se-labs/attendee/concourse/tasks/build.sh
  args: [
    --input-dir, ./se-labs/attendee,
    --output-dir, build,
    --version-file, version/number,
    --artifactId, attendee,
    --packaging, jar
  ]
